// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRb-bzfBrSDKYoRxHIrgeYNvM1WU0HUu0',
    appId: '1:883905823453:web:294d186a0f41e693075134',
    messagingSenderId: '883905823453',
    projectId: 'safeher-776e3',
    authDomain: 'safeher-776e3.firebaseapp.com',
    storageBucket: 'safeher-776e3.firebasestorage.app',
    measurementId: 'G-MM65DKH787',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc9K6Dycm40mt6bL_ifPyu2VlvGbh237U',
    appId: '1:883905823453:android:a2ec3d35d4fdccfd075134',
    messagingSenderId: '883905823453',
    projectId: 'safeher-776e3',
    storageBucket: 'safeher-776e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFsvgFmIogJ_0w2hO_zST81yV1v0-3x9g',
    appId: '1:883905823453:ios:0bc5c3ae23d82d9f075134',
    messagingSenderId: '883905823453',
    projectId: 'safeher-776e3',
    storageBucket: 'safeher-776e3.firebasestorage.app',
    iosClientId: '883905823453-sa2mtro05hd658jps2neecfcsf1o6b7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.safer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFsvgFmIogJ_0w2hO_zST81yV1v0-3x9g',
    appId: '1:883905823453:ios:0bc5c3ae23d82d9f075134',
    messagingSenderId: '883905823453',
    projectId: 'safeher-776e3',
    storageBucket: 'safeher-776e3.firebasestorage.app',
    iosClientId: '883905823453-sa2mtro05hd658jps2neecfcsf1o6b7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.safer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRb-bzfBrSDKYoRxHIrgeYNvM1WU0HUu0',
    appId: '1:883905823453:web:20371a41111e2fe3075134',
    messagingSenderId: '883905823453',
    projectId: 'safeher-776e3',
    authDomain: 'safeher-776e3.firebaseapp.com',
    storageBucket: 'safeher-776e3.firebasestorage.app',
    measurementId: 'G-9H6FRKVLCN',
  );
}
